
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import React from 'react';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <AppBar position="static" style={{backgroundColor: "#09215D"}}>
        <Toolbar>
          <div className='row col-sm-12'>

            <div className='col-sm-6'>
              <Typography variant="h6" style={{color: "#FFD23B"}}>
                Nk System
              </Typography>
            </div>
            <div className='col-sm-6 row'>
              <div className='col-sm-3'>
                <Typography variant="h6" style={{color: "#FFD23B"}} >
                  Home
                </Typography>
              </div>
              <div className='col-sm-3'>
                <Typography variant="h6" style={{color: "#FFD23B"}} >
                  Plano
                </Typography>
              </div>
              <div className='col-sm-3'>
                <Typography variant="h6" style={{color: "#FFD23B"}} >
                  Sobre Nós
                </Typography>
              </div>
              <div className='col-sm-3'>
                <Typography variant="h6" style={{color: "#FFD23B"}} >
                  Contato
                </Typography>
              </div>
            </div>

          </div>


        </Toolbar>
      </AppBar>
        {children}
      </body>
    </html>
  )
}
