"use client";
import React from 'react';
import { useRouter } from 'next/navigation'

import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import Fade from '@mui/material/Fade';
import Link from 'next/link';
import MenuIcon from '@mui/icons-material/Menu';
import './globals.css'

import { styled } from '@mui/material/styles';
import { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter();
  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
  const open = Boolean(anchorEl);
  
  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = () => {
    setAnchorEl(null);
  };
  
  const handleCloseSobre = () => {
    router.push('/sobre-nos', { scroll: false })
    setAnchorEl(null);
  };

  const handleClosePlanos = () => {
    router.push('/planos', { scroll: false })
    setAnchorEl(null);
  };

  const handleCloseContato = () => {
    router.push('/contato', { scroll: false })
    setAnchorEl(null);
  };

  return (
    <html lang="en">
      <body >


          <AppBar position="fixed" style={{ backgroundColor: "#1D62AF", zIndex: 1, width: '100%' }}>
            <Toolbar>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
                <Link href="/">
                  
                  <img src='https://i.ibb.co/VVnwJ05/nk.png' style={{width: 45}} className='img-fluid col-sm-1' />
                </Link>
                <div className="d-none d-md-flex" style={{ width: '30%' }}>
                    <Link href="/sobre-nos">
                      <Typography style={{margin: 10, color: '#F7B41E'}}>
                        Sobre
                      </Typography>
                    </Link>
                    <Link href="/planos">
                      <Typography style={{margin: 10, color: '#F7B41E'}}>
                        Plano
                      </Typography>
                    </Link>
                    <Link href="/login">
                      <Typography style={{margin: 10, color: '#F7B41E'}}>
                        Area do Cliente
                      </Typography>
                    </Link>
                    <Link href="/contato">
                      <Typography style={{margin: 10, color: '#F7B41E'}}>
                        Contato
                      </Typography>
                    </Link>
                </div>

                <div className='mobile' style={{ width: '11%' }}>
                  <Button
                    id="basic-button"
                    aria-controls={open ? 'basic-menu' : undefined}
                    aria-haspopup="true"
                    aria-expanded={open ? 'true' : undefined}
                    onClick={handleClick}
                    style={{color: 'white'}}
                  >
                    <MenuIcon/>
                  </Button>
                  <Menu
                    id="basic-menu"
                    anchorEl={anchorEl}
                    open={open}
                    onClose={handleClose}
                    MenuListProps={{
                      'aria-labelledby': 'basic-button',
                    }}
                  >
                    <MenuItem onClick={handleCloseSobre}>Sobre</MenuItem>
                    <MenuItem onClick={handleClosePlanos}>Planos</MenuItem>
                    <MenuItem onClick={handleCloseContato}>Contato</MenuItem>
                  </Menu>
                </div>
              </div>
            </Toolbar>
          </AppBar>
          {children}

          <footer className="" style={{backgroundColor: "#1D62AF"}}>

            <section  className=" border-bottom" style={{paddingTop: 0}}> </section>

              <div className="container text-center text-md-start mt-5">

                <div className="row mt-3">

                  <div className="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

                    <h6 className="text-uppercase fw-bold mb-4">
                      <Link href="/">
                        <img src='https://i.ibb.co/VVnwJ05/nk.png' style={{width: 50}} className='img-fluid col-sm-1' />
                      </Link>
                    </h6>
                    <p>
                      Transforme sua Era Digital
                    </p>
                  </div>

                  <div className="col-md-3 col-lg-2 col-xl-2 mx-auto mb-6" style={{paddingBottom: 150}}>
                    <Link href="/sobre-nos">
                      <Typography style={{margin: 10, color: '#F7B41E'}}>
                        Sobre
                      </Typography>

                    </Link>
                    <Link href="/planos">
                      <Typography style={{margin: 10, color: '#F7B41E'}}>
                        Plano
                      </Typography>
                    </Link>
                    <Link href="/login">
                      <Typography style={{margin: 10, color: '#F7B41E'}}>
                        Area do Cliente
                      </Typography>
                    </Link>
                    <Link href="/contato">
                      <Typography style={{margin: 10, color: '#F7B41E'}}>
                        Contato
                      </Typography>
                    </Link>

                  </div>

    
                </div>

              </div>


              <div className="text-center p-4" style={{backgroundColor: '#1F1F1F', color: 'white'}}>
                © 2021 Todos os Direitos Reservados:
                <a className="text-reset fw-bold" href="https://nksystem.com.br/"> nksystem.com.br</a>
              </div>

          </footer>


      </body>
    </html>
  )
}
